name: Corexizen
version: '$version'

main: org.isnsest.corexizen.Corexizen
api-version: '1.21'

authors: [ isnsest ]

dependencies:
  server:
    Denizen:
      load: BEFORE
      required: true
      join-classpath: true
    Corex:
      load: BEFORE
      required: true
      join-classpath: true